---
ID: "52872dac-2988-4397-89b9-e05299497dce"
Parent: "e10e97fe-2346-4bf1-b08d-badf9f095b38"
Template: "e10e97fe-2346-4bf1-b08d-badf9f095b38"
Path: /sitecore/templates/Project/xyz/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211217T085735Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
