---
ID: "75357ecd-fac5-40e2-975a-4007b0841bd7"
Parent: "af29aea0-7c27-4897-b806-ffbeab9d4723"
Template: "af29aea0-7c27-4897-b806-ffbeab9d4723"
Path: /sitecore/templates/Project/DemoSite/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211216T090313Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
