---
ID: "c9efe30c-75b2-4c26-9e3c-c380f04a4bb9"
Parent: "4a922716-3ecc-4c7c-bcc2-b6d0201d6f1e"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/xyz/DigitalAI/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211217T085839Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
