---
ID: "7cfbf7e0-331e-42d7-b2d4-b334050e7ffe"
Parent: "d1e59d5b-52ca-4cad-9185-fb6299a41cc4"
Template: "d1e59d5b-52ca-4cad-9185-fb6299a41cc4"
Path: /sitecore/templates/Project/DemoSite/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211216T090314Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
